### ISSUE TITLE
Missing dependency in Python 3.7

### ISSUE THREAD

**Issue by jacklovell** [newville/asteval#101]
`importlib_metadata` should be listed as a dependency in Python 3.7, as mentioned in https://github.com/newville/asteval/issues/93#issuecomment-866803718 and https://github.com/newville/asteval/pull/94#pullrequestreview-690394299. Both those comments were made after the respective issue and PR were closed, so were maybe missed but this is still a problem.

**Comment by newville** [comment]
@jacklovell oh, sorry for forgetting that.  Will fix.

**Comment by newville** [comment]
Should be fixed with a79183d4928aceacd05c2dfa720d6db2deec4af3
I hope to find time to migrate to `setup.cfg` + `pyproject.toml` and then push out a release soon.

**Comment by jacklovell** [comment]
Thanks, looks to work fine now.
