### ISSUE TITLE
List comprehension with multiple "for" loops results in NameError

### ISSUE THREAD

**Issue by sethw-xilinx** [newville/asteval#108]
Steps to reproduce:
```
import asteval

single_loop = """
[a for a in range(10)]
"""

double_loop = """
[(a,b) for a in range(10) for b in range(10)]
"""
aeval = asteval.Interpreter(use_numpy=False)

print(aeval.eval(single_loop))
print(aeval.eval(double_loop))
```

Results in the following output:
```
$ python3 ~/temp/astevaltest.py
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
NameError

[(a,b) for a in range(10) for b in range(10)]

        ^^^
name 'b' is not defined
```

This is not the same as a conventional python eval, which will evaluate the `double_loop` string as you would expect:
```
>>> eval("[(a,b) for a in range(10) for b in range(10)]")
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9)]
>>>
```

**Comment by newville** [comment]
@sethw-xilinx Thanks for raising this.   I guess that needs some study on how to fix it.

**Comment by pwestlak-xilinx** [comment]
@newville I guess it's to do with `on_listcomp` only assigning one variable?

**Comment by newville** [comment]
@pwestlak-xilinx @sethw-xilinx  I think it is actually the assignment aspect that is messed up. Hopefully, I'll have time to look at this in detail this week.

**Comment by newville** [comment]
@pwestlak-xilinx @sethw-xilinx OK this took longer than expected - I could not reason how to do this for an arbitrary number of list comprehensions (might be missing something obvious!) but did implement this for up to 4 comprehensions loops. 
So "fixed in master", but that's not to say it could not be further improved!

**Comment by sethw-xilinx** [comment]
@newville I think I spotted something obvious - I've made PR109 as an improvement. Please take a look and let me know if there are any issues :)

**Comment by newville** [comment]
@sethw-xilinx Yes, thanks very, very much!
