### ISSUE TITLE
Support regex / glob modules

### ISSUE THREAD

**Issue by moloney** [newville/asteval#111]
One potential use case for this package is to avoid writing a DSL for selecting / filtering data. However the ability to work with strings is quite limited compared to numbers. Adding access to at least some of the `glob` and `re` modules would make this use case much more viable.

**Comment by newville** [comment]
@moloney Is something like
 
```python
    from glob import glob 
    import re
    import asteval
    aeval = asteval.Interpreter(usersyms={'glob': glob, 're': re})
    flist = aeval("glob('*')")
```

acceptable?

**Comment by moloney** [comment]
My concern would be, for example, unintentionally providing a reference to the `os` or `sys` modules through the `re` module. I guess it does make sense to leave it to users to sanitize the stuff they expose if it is a niche request.
