### ISSUE TITLE
PyPI: also upload source tarball

### ISSUE THREAD

**Issue by reneeotten** [newville/asteval#113]
hi @newville - would it be possible to upload the source archive instead of only a `.whl` file? 

I am packaging it for MacPorts and see the typical issues with `setuptools_scm` as the GitHub tarball does not contain the `asteval/version.py` file and thus one gets the following error:
```
LookupError: setuptools-scm was unable to detect version for /opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-asteval/py310-asteval/work/asteval-0.9.28.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

**Comment by newville** [comment]
@reneeotten Thanks -- should be there now!

**Comment by reneeotten** [comment]
indeed - thanks!
