### ISSUE TITLE
power to a negative int

### ISSUE THREAD

**Issue by ccomb** [newville/asteval#115]
Hi, there is someting I don't understand with `safe_pow`

```
>>> import asteval
>>> 2**-2
0.25
>>> asteval.Interpreter()("2**-2")
0
>>> 
```

Why is there a conversion to int in the result of the `safe_pow` function?
 
```
          if isinstance(exp, int): 
              return int(ret)                                        
```
Here: https://github.com/newville/asteval/blob/master/asteval/astutils.py#L226

**Comment by ccomb** [comment]
My intuition tells me that it comes from an old Python 2 compatibility requirement that's no longer relevant since asteval now requires py>3.7

**Comment by newville** [comment]
@ccomb Thanks.  Yes, I think your assessment is correct: this should have gone away when dropping Py2 support, and it just got forgotten.   Will merge #116.

**Comment by ccomb** [comment]
Thanks @newville !
Is the next release already planned?
