### ISSUE TITLE
Quiet Mode

### ISSUE THREAD

**Issue by CarstVaartjes** [newville/asteval#26]
Hi,

we use asteval a lot, thanks for the great package! 
However, something that used to work, doesn't seem to work anymore, which is surpressing the text output (it can really swamp terminal output with things that aren't issues).
We had this solution in place:

    class FakeWriter(object):
        def __init__(self):
            def fake_write(*args):
                pass

            self.write = fake_write

    f = Interpreter(writer=FakeWriter())
    f('1.0 / 0.0')

This used to work fine, but not anymore. Now we get still stdout for the zero division error. What changed? Is there any way to surpress it better?
We upgraded to the latest version, 0.9.8

BR

Carst

P.s. the following does work:

    f('try:\n    1.0 / 0.0\nexcept:\n   pass')

but that seems to be a bit over kill to me?

**Comment by CarstVaartjes** [comment]
Ah sorry, just heard about the err_writer. sorry about that!

**Comment by newville** [comment]
@CarstVaartjes Glad you got this to work.   We probably need to improve the docs to include this and other initialization-time options.
