### ISSUE TITLE
error_msg not being cleared between eval() runs

### ISSUE THREAD

**Issue by mnolet** [newville/asteval#27]
Hello -- loving asteval!  Thanks for putting this on github.

I would submit as a commit but not super confident I'm right so adding as an issue.

In `eval()` currently it resets `self.error = []` but does *not* reset `self.error_msg`

This means that if you call `eval(*args,show_errors=False)` you end up with an incrementally growing error list.

I think all that's needed is a simple `self.error_msg = None` in the first few lines of `def eval()`

Cheers,

-Mike

**Comment by newville** [comment]
@mnolet  Yeah, I see that could be a problem.  Can you provide a test case?

**Comment by newville** [comment]
@mnolet I added your suggested `self.error_msg = None` to the top of `eval()`, this is now in github master, 705d30a0ed9fdf886084ddfa59ccf013f0ee3532.   Please let me know if this is not working for you.
