### ISSUE TITLE
Problem with functions defined inside asteval.Interpreter

### ISSUE THREAD

**Issue by alemarmed** [newville/asteval#28]
Hi, I'm using asteval to evaluate python code stored in database and it's awesome. But for my use case I need lot of functions definitions and there is something that I really don't understand. I found a very simple test:

```
aeval = Interpreter()
code = """
def a():
    return 1
def b():
    return 2
def c():
    return a() + b()
c()
"""
aeval(code)  # returns 3
aeval = Interpreter()
code = """
def a():
    return 1
def b():
    return 2
def c():
    x = a()
    y = b()
    return x + y
c()
"""
aeval(code)  # returns 1
```

Are functions defined inside the interpreter only working in one-line statements? Thanks for your work!

**Comment by newville** [comment]
@alemarmed  Sorry for the trouble.   That looks like a bug with how "return" is handled.   I think that is solvable, but I'll have to look into it a bit more thoroughly.

**Comment by newville** [comment]
@alemarmed  I think this is now fixed in github master 705d30a0ed9fdf886084ddfa59ccf013f0ee3532  Please let me know if it is not working for you.

**Comment by alemarmed** [comment]
@newville I just checked out master and it works well. Thanks for quick resolution!

**Comment by newville** [comment]
@alemarmed Great, thanks for verifying!
