### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by wcpettus** [newville/asteval#38]
Now when attempting to `pip install asteval`, it fails saying it can't import module six.  When I asked on stackoverflow someone said this was because your setup.py imports asteval? (https://stackoverflow.com/questions/47127178/pip-install-asteval-fails-on-six-dependency)

I'm out of my depth here, but would really like asteval installation to work again.

**Comment by newville** [comment]
@wcpettus Oh, very sorry. That is a silly mistake on my part.  Will fix soon to use versioneer.py.  To work with PyPI, I'll have to release that as 0.9.11

**Comment by newville** [comment]
@wcpettus should be fixed now.  Can you verify?

**Comment by wcpettus** [comment]
Yes, this is working again in 0.9.11.  Thanks @newville.
