### ISSUE TITLE
string format broken

### ISSUE THREAD

**Issue by wcpettus** [newville/asteval#39]
In asteval 0.9.8, I could do this:
```python
>>> import asteval
>>> i = asteval.Interpreter()
>>> i('"hello world {}".format(2)')
'hello world 2'
```

Now in asteval 0.9.11, this is broken:
```python
>>> import asteval
>>> i = asteval.Interpreter()
>>> i('"hello world {}".format(2)')
AttributeError
   "hello world {}".format(2)
'hello world {}' object has not attribute 'format'
```

Was this an intentional break and is there an explanation of why the new release did this?  Or did I stumble on a bug?

**Comment by newville** [comment]
@wcpettus Yes, `str.format` was purposely removed from asteval 0.9.9, as it is unsafe.  
See #32 (especially toward end of that discussion).
