### ISSUE TITLE
test_dos fails on recursion

### ISSUE THREAD

**Issue by jmdejong** [newville/asteval#44]
When trying to run the tests python stops reacting and starts eating cpu and memory once it reaches test_dos.
Some debug prints suggested that the culprit is in the recursion test.
In that test the debug prints kept going for about 0.03 seconds and then just stopped while the test went out of control.

I have tested this in both Python 3.7.0 and Python 2.7.15.
I am running ArchLinux 64-bit

**Comment by newville** [comment]
@jmdejong Hm, not sure what's going on.  I don't see that with Python 2.7.15 on 64-bit linux (Fedora28, using Anaconda Python 2.7.15).  I haven't tried 3.7 yet.  Any clues?

**Comment by jmdejong** [comment]
I believe it's in the error handling of RecursionErrors.

After messing around a bit I think I the problem is in those lines:
https://github.com/newville/asteval/blob/cca7e6621be39974f0a566907d1edba3e4a09d52/asteval/asteval.py#L757-L762
and
https://github.com/newville/asteval/blob/cca7e6621be39974f0a566907d1edba3e4a09d52/asteval/asteval.py#L293-L300

About when it is deep enough in recursion the python interpreter will call a RecursionError
Somewhere after catching this error the program starts running away.
I haven't figured out yet how or why.

My recursion limit is 1000 by the way (for both python 2 and 3)

**Comment by jmdejong** [comment]
The problem is not infinite looping/recursion, it turns out to be the exponential growth of error messages!

https://github.com/newville/asteval/blob/cca7e6621be39974f0a566907d1edba3e4a09d52/asteval/asteval.py#L242
https://github.com/newville/asteval/blob/cca7e6621be39974f0a566907d1edba3e4a09d52/asteval/asteval.py#L248
https://github.com/newville/asteval/blob/cca7e6621be39974f0a566907d1edba3e4a09d52/asteval/asteval.py#L760-L762

on_call will call raise_exception with a custom message including the message of the exception that was caught.
raise_exception will add this message to the current messages.
Then it will and then re-raise with all current messages as message.

With each iteration of this the size of the current messages will double.
For 30 levels of nested error throwing this is already gigabytes of data.
A simple recursive function with an `if` will hit the recursion limit at about `python_recusion_limit/8` iterations, in my case around 120 iterations.

**Comment by newville** [comment]
Hm, OK thanks for the update. I'm not sure why this is only now a problem...  But I'm also not sure why it doubles with each step instead of growing linearly with step.

Perhaps we should limit the length of `self.error_msg`?  I don't know for sure that this will fix the problem.  For sure there is *supposed* to be a RecursionError raised here....

**Comment by jmdejong** [comment]
Yes there is a RecursionError here. That's what originally triggers these exceptions.

Lines 761 an 762 were only implemented like this a month ago, that would explain why it wasn't seen before.

It could be possible that you and travis have a lower recursion depth limit.
If your limit would be 100 the evaluated code would only nest to about 20 levels I think. This results in only a few megabytes of error messages and most systems can deal with that

So what is happening is that `raise_exception` is called, it raises an exception and the next level up the call stack it is caught, and then that exception handler calls `raise_exception` again etc...
Line 242 comes down to:
    self.error_msg = self.error_msg + msg
and the other lines come down to
    msg = self.error_msg
So this in combination comes down to
    self.error_msg = self.error_msg + self.error_msg


Limiting the length of `self.error_msg` would probably solve the problem but it would also probably be an ugly solution.
I think my preferred solution would be to not use `self.error_msg` at all. The error message can just bubble up through the exceptions then.

**Comment by newville** [comment]
@jmdejong Ah, sorry, I was getting 0.9.12 not the master branch, from some oddity of python eggs.  With master-branch I *can* see the problem with Python 2.7.

**Comment by chrisjbremner** [comment]
> I'm not sure why this is only now a problem...

Haven't looked into it much, but it could be related to #42 and #43

**Comment by newville** [comment]
calling this closed...
