### ISSUE TITLE
Exception handling incorrect

### ISSUE THREAD

**Issue by jmdejong** [newville/asteval#52]
Several things seem to go wrong with the execption handling.
This code:

    def foo():
        raise Exception("error in function")

    try:
        foo()
        print("still going on")
        raise Exception("directly raised error")
    except Exception:
        print("error caught")

Gives as result:

    error caught
    still going on
    Exception
   
    directly raised error

(The last 3 lines are the printed error)

There are 2 things going wrong here:
- When a raised exception is caught the rest of the try block will still be executed
- Catching some exception type does not catch exceptions that are raised directly in that try block

These problems are unrelated: they also show up when I test for them individually.

Another problem is that catching named errors doesn't work.

    def foo():
        raise Exception("error in function")

    try:
        foo()
    except Exception as ex:
        print("caught:", ex)

gives:

    NameError
       <>
                             ^^^
    name 'ex' is not defined

**Comment by newville** [comment]
@jmdejong Perhaps it would be better to lump all problems with exception handling in a separate branch, and then make a single PR about that.  That is, creating a new Issue or PR for different related problems probably isn't that useful.

**Comment by chrisjbremner** [comment]
I believe this has been fixed and can be closed? I attempted to recreate this with the latest code, and it ran as you'd expect:

```python
In [1]: import asteval

In [2]: aeval=asteval.Interpreter()

In [3]: code="""
   ...: def foo():
   ...:     raise Exception("error in function")
   ...: 
   ...: try:
   ...:     foo()
   ...:     print("still going on")
   ...:     raise Exception("directly raised error")
   ...: except Exception:
   ...:     print("error caught")
   ...: """

In [4]: aeval.eval(code)
error caught
```

**Comment by newville** [comment]
@chrisjbremner Yes, I will close this.
