### ISSUE TITLE
Python 3.X print() works with no_print=True

### ISSUE THREAD

**Issue by kzimmer-bah** [newville/asteval#55]
While I know the python 3.x `print()` function is not designed to be blocked by the `no_print=True` setting, is there a plan to implement this? As a temporary workaround, I have simply removed `print` from the symtable whenever `no_print` is set. This prevents the symbol from being loaded in the `on_name()` call [here](https://github.com/newville/asteval/blob/3410fd88601ad1d7e509e8c60f7a48eb7bbd4405/asteval/asteval.py#L448-L452). I'm not sure if that's the best way to address this and haven't tested this enough to see if it breaks other sections of the interpreter.

**Comment by newville** [comment]
@kzimmer-bah  I think that's a fine way of doing it.   Another approach would be to add an explicit test in `on_call()` for `func==print and no_print` and refuse to do the function call there.

Possibly related: we could declare the end of Python 2.7 support at any point now (even, right now), which would allow us to drop `on_print` and `printer`, and might allow us to have  `no_print`  do something like:

```
      print_func = __builtins__.print
      if no_print:
            def print_nowhere(*args, **kws): pass
            .print_func = print_nowhere
     symtable['print'] = print_func
```

**Comment by newville** [comment]
@kzimmer-bah  I believe this is now fixed so that `no_print` works to suppress printing with python3
