### ISSUE TITLE
Add support for Unicode identifiers

### ISSUE THREAD

**Issue by natezb** [newville/asteval#56]
Non-ASCII identifiers have been available since Python 3.0, and are described [here](https://docs.python.org/3/reference/lexical_analysis.html#identifiers). Currently, `valid_symbol_name()` does not accept such characters. I encountered this issue when using `lmfit`, a situation where using such identifiers would be very useful.

I might be willing to issue a PR to fix this if it's not too involved--are there any other places in the code that might need to be modified, other than `valid_symbol_name()`?

**Comment by natezb** [comment]
How do you feel about using the stdlib `tokenize` module? It should be pretty trivial to implement this change using it.

If that's fine, then the question is: do we use the old method with this new method, or do we use it as a fallback to double-check non-ASCII strings that have failed the first test? If the new method is slow, it might merit the second approach, but otherwise a simple replacement might be the better option.

**Comment by newville** [comment]
@natezb I don't have a strong preference about this.  That is, I think it would generally be a bad idea to use non-ASCII as identifiers in code, but I don't know why we should prevent someone from doing that.

I don't know whether `valid_symbol_name()` is the only place the "ASCII only" assumption is made, but it would definitely be the place to start.   One approach might be to have `valid_symbol_name()` short-circuit to always return `True` and figure out where downstream code fails.

Does `tokenize` help?   I think it would be OK to use anything from the standard library, but I'm not seeing immediately how that module would help.
