### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by reneeotten** [newville/asteval#62]
@newville I tried to do some testing with Python 3.8 and ```lmfit```, which I will try to add to Travis after we release v0.9.14. It seems though that most of the issues I noticed were actually related to ```asteval```.

All the test pass with Python 3.7, but there are many failures with the latest ```beta3```: 
``` ======================== 42 failed, 15 passed in 2.04s =========================```

I haven't carefully looked at it yet, but just wanted to see if you had done some work/testing on this already. There is more than a month left before the planned release, but it might be worthwhile to take a look at this before that actually happens.

**Comment by newville** [comment]
@reneeotten  I have not tried 3.8 yet.  It is not uncommon that each release changes AST a bit, but that seems like a lot of failures -  I hope that is really repeats of a smaller set of errors!

**Comment by newville** [comment]
@reneeotten   I *think* this is fixed.  That is, it now works for me with Python 3.8b4.  FWIW, it was one smallish change repeated often.

**Comment by reneeotten** [comment]
@newville yep, that seemed to have fixed it indeed. As you can see, the tests for ```lmfit``` now pass for Python 3.8 as well. Thank you, I'm closing this issue!

**Comment by reneeotten** [comment]
@newville would it be possible to release a new version that is compatible with Python 3.8?

**Comment by newville** [comment]
@reneeotten I believe this is now done with the release of `asteval 0.9.16`.  I'll leave open until we're convinced there are no problems...

**Comment by reneeotten** [comment]
I haven't seen any issues yet, so let's instead close this until someone finds anyything ;)
