### ISSUE TITLE
Strange behaviour when asteval throws an exception

### ISSUE THREAD

**Issue by bek0s** [newville/asteval#63]
Hello,

I have the following code:

```python
import asteval
expreval = asteval.Interpreter(minimal=True, use_numpy=False)
expreval("a=sin('1')")
for error in expreval.error:
    print(error.get_error())
```

When I run it, it produces the following output:

```
TypeError
   a=sin('1')
      ^^^
Error running function call 'sin' with args ['1'] and kwargs {}: must be real number, not str
('TypeError', "   a=sin('1')\n      ^^^\nError running function call 'sin' with args ['1'] and kwargs {}: must be real number, not str")
('TypeError', "   a=sin('1')\n      ^^^\nat expr='a=sin('1')'")
('TypeError', "   a=sin('1')\nat expr='a=sin('1')'")
('TypeError', "   a=sin('1')\nat expr='a=sin('1')'")
```

I am a bit confused as to why the code results in 4 errors instead of one. To me, it seems that only `expreval.error[0]` should be generated. Is this a bug or a feature? Or maybe I am missing something?

Thank you

PS: I am using Python 3.7

**Comment by chrisjbremner** [comment]
Hi @bek0s, this should be resolved by https://github.com/newville/asteval/pull/64. Hopefully @newville will cut a new release soon so you can update the package using pip. @newville it looks like you need to close this issue too, since I don't have the ability to do so.

**Comment by newville** [comment]
@bek0s @chrisjbremner OK, closing, and I will push a new release within a day or two...
