### ISSUE TITLE
asteval Interpreter not deep copyable

### ISSUE THREAD

**Issue by bek0s** [newville/asteval#67]
Hello,

I have been using this amazing library in my software for some time now, and just today I run into a very strange problem. For some reason, I need to deep copy an object which includes an `asteval.Interpreter` as a member variable. Unfortunately, this does not work.

#### Reproducing code example:
```
import copy
import asteval
aeval = asteval.Interpreter(minimal=True, use_numpy=False)
copy.deepcopy(aeval)
```
#### Error message:
```
    copy.deepcopy(aeval)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.TextIOWrapper' object
```
#### Thoughts:
After doing some Googling, I found people saying that this problem can be caused when trying to deep copy objects that include files. So I did the following:
```
import copy
copy.deepcopy(open("foo.txt", "w"))
```
Indeed, the above produced the same exception at the same line, but the call stack is shallower:
```
copy.deepcopy(open("foo.txt", "w"))
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.TextIOWrapper' object
```
I would like to ask if someone knows whether asteval is deliberately not deep copyable or this is a bug.

Thank you for your time.

**Comment by newville** [comment]
@bek0s I'm going to close this.  For your ultimate question:

`I would like to ask if someone knows whether asteval is deliberately not deep copyable or this is a bug.`

The answer is "neither".  Some Python objects, including (as your exception shows, the Python builtin `_io.TextIOWrapper`) cannot be serialized for copy/deepcopy (or pickling as might be used for multiprocessing).   

This is not "deliberate" on the part of `asteval` and it is not a `bug`.  It is a limitaion of Python's serialization, pickling, and copying.
