### ISSUE TITLE
Disable warning when numpy is not available

### ISSUE THREAD

**Issue by bblanchon** [newville/asteval#7]
> Warning: numpy not available... functionality will be limited.

This is quite annoying, especially when you call `Interpreter(use_numpy=False)`.
I think it should only appear when `use_numpy=True`

An alternative would be to set the default to `use_numpy=False` and throw an error if `use_numpy=True` and the module is not installed.

**Comment by tals** [comment]
+1 to removing the error printing. It's really annoying.

**Comment by tals** [comment]
I just realized you already removed it. Could you upload an updated version to pypi?

**Comment by newville** [comment]
Hi, yeah that's a reasonable request. I think there might be another small
issue with pickling exposed from a related library.  Ill work on this soon.
