### ISSUE TITLE
kwargs don't seem to be passed down correctly

### ISSUE THREAD

**Issue by yoggi-yalla** [newville/asteval#79]
First of all, thank you for a very useful library! I've found a slight issue with how kwargs are passed down recursively. Here is an example of what I mean:

```python
from asteval import Interpreter
aeval = Interpreter()

inner = \
"""
def inner(foo=None,bar=None):
    print(foo, bar)
"""

outer = \
"""
def outer(**kwargs):
    inner(**kwargs)
"""

aeval(inner)
aeval(outer)

aeval("inner(foo='baz', bar=123)") # this one works
aeval("outer(foo='baz', bar=123)") # this one does not
```

For completeness, here is the same code in regular python which works fine:
```
def inner(foo=None,bar=None):
    print(foo,bar)

def outer(**kwargs):
    inner(**kwargs)

outer(foo='baz', bar=123)
```

With the following tweak in asteval.py (row 746) it seems to behave like expected:
```python
        while len(keywords) == 1 and None in keywords.keys():
            keywords = keywords[None]
```
But I'm sure there's a more correct way to solve it. Any help on this would be much appreciated!

**Comment by newville** [comment]
@yoggi-yalla Ah, thanks for the report - I can confirm that and will investigate the best solution.

**Comment by newville** [comment]
@yoggi-yalla may be fixed with 87007636d73 - tests based on your example work for me, we'll see if all tests pass.

**Comment by yoggi-yalla** [comment]
Thanks for the quick turnaround, seems to work just fine now!

**Comment by yoggi-yalla** [comment]
@newville are there any plans to make a new release to pypi including this fix?

**Comment by newville** [comment]
@yoggi-yalla I will try to push out 0.9.22 in the next few days...

**Comment by newville** [comment]
0.9.22 released!

**Comment by yoggi-yalla** [comment]
Thanks Matt!
