### ISSUE TITLE
Security issue - the 'os.system' method is still accessible

### ISSUE THREAD

**Issue by kpounot** [newville/asteval#81]
Hi everyone,

It seems that most of the python language is still accessible with asteval when we use aliases.

For example, here is a small code to create two directories and remove one:

``` python
from os import system as y
import asteval

aeval = asteval.Interpreter()

aeval.symtable['y'] = y

aeval("y('mkdir test1 test2')")
aeval("y('rm -rf test1')")
```

The same could be done with "aeval('rm -rf /')".

There might be a way to make it safer if all function calls are filtered using a ast.NodeTransformer. Then for each 'ast.Name' associated with the 'ast.Call', just replace the name by a dictionary entry which contains the truly expected function.
However, this implies making the symtable read-only, and thus strongly limit the *asteval* capabilities.

For example, when I write:

``` python
aeval("exp(-x**2 / (2 * sigma)")
```
We can use the ast.NodeTransformer to change the string to "symtable['exp'](-x**2 / (2 * sigma))", where 'symtable' is read-only and point here to the numpy exponential function.

**Comment by newville** [comment]
@kpounot FWIW, all function calls are sent through `ast.Call` and `ast.Name` and are taken from `symtable`. 

What your script does is add a callable (`os.system`) **FROM PYTHON**.    The person writing a python program *can* add custom symbols.   Obviously, they can also import and use `os.system` from Python ;).  But one cannot import `os` or any other external module from within the asteval interpreter itself.   One can create symbols, including callable functions, from within the interpreter.  

The safety we're looking for here is about what a user can do from within asteval.  The examples would be if you wanted to use asteval to expose a python-like calculator in a web interface or from an application run with administrative privileges, etc.  If you exposed *python* as a calculator, there would be concerns about being able to import `os` or any number of other modules.

**Comment by kpounot** [comment]
Ok, many thanks Matt.

I as thinking of something more strict like the 'ast.literal_eval()' but with extended features.

Indeed, I guess no much harm can be done if only asteval is exposed.

I close this issue then.
