### ISSUE TITLE
Add classifiers to show Python 3 support

### ISSUE THREAD

**Issue by cmutel** [newville/asteval#9]
Not sure what you think is appropriate, but something like the following would be nice:

    classifiers=[
      'Intended Audience :: End Users/Desktop',
      'Intended Audience :: Developers',
      'Intended Audience :: Science/Research',
      'License :: OSI Approved :: BSD License',
      'Operating System :: MacOS :: MacOS X',
      'Operating System :: Microsoft :: Windows',
      'Operating System :: POSIX',
      'Programming Language :: Python',
      'Programming Language :: Python :: 2.6',
      'Programming Language :: Python :: 2.7',
      'Programming Language :: Python :: 3.2',
      'Programming Language :: Python :: 3.3',
     ],

**Comment by newville** [comment]
done!
