### ISSUE TITLE
Import  error with python 3.7 due to missing import.metadata 

### ISSUE THREAD

**Issue by MWBASF** [newville/asteval#93]
Unfortunately, for python 3.7 importlib.metada does not exist. Therefore, the _version.py file of this package causes an package import error.
Other packages (e.g. jsonschema 3.2) use this compatibility code to fix the issue:

try:
    from importlib import metadata
except ImportError: # for Python<3.8
    import importlib_metadata as metadata

**Comment by caenrigen** [comment]
This also breaks packages like `lmfit`:

```python
import lmfit
```

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-42f2a570039d> in <module>
----> 1 import lmfit

/usr/local/anaconda3/envs/q37/lib/python3.7/site-packages/lmfit/__init__.py in <module>
     34 
     35 """
---> 36 from asteval import Interpreter
     37 
     38 from .confidence import conf_interval, conf_interval2d

/usr/local/anaconda3/envs/q37/lib/python3.7/site-packages/asteval/__init__.py in <module>
     25            'make_symbol_table', 'get_ast_names']
     26 
---> 27 from ._version import __version__

/usr/local/anaconda3/envs/q37/lib/python3.7/site-packages/asteval/_version.py in <module>
      3 __release_version__ = '0.9.24'
      4 
----> 5 from importlib.metadata import version, PackageNotFoundError
      6 try:
      7     __version__ = version("asteval")

ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by newville** [comment]
oh, my mistake and very sorry for the mess -- I'm trying to understand why the CI at https://github.com/newville/asteval/actions/runs/959037623
reports success for Python 3.6 and 3.7.  It looks like that testing is misconfigured, always using Python 3.8! Yikes.

I will revert to versioneer, effectively reverting to  b114a3ea31f736f4a87911c32fa08febb1107c9c and checking that the tests use all versions.  When that passes, I'll tag that as 0.9.25 and push out.  I'm hoping that is within hours.

**Comment by caenrigen** [comment]
> oh, my mistake and very sorry for the mess -- I'm trying to understand why the CI at https://github.com/newville/asteval/actions/runs/959037623
> reports success for Python 3.6 and 3.7. It looks like that testing is misconfigured, always using Python 3.8! Yikes.
> 
> I will revert to versioneer, effectively reverting to [b114a3e](https://github.com/newville/asteval/commit/b114a3ea31f736f4a87911c32fa08febb1107c9c) and checking that the tests use all versions. When that passes, I'll tag that as 0.9.25 and push out. I'm hoping that is within hours.

Hi, thank you for the reply :)
maybe there is no need for a revert, see my #94, making sure the CI tests for python 3.7 should be enough I am guessing

**Comment by newville** [comment]
@caenrigen Yes, good point -- will merge that, and also try to make sure the CI script is working correctly!

**Comment by pelson** [comment]
Just wanted to add that there is now a missing dependency declaration, as per https://github.com/newville/asteval/pull/94#pullrequestreview-690394299, which means this issue shouldn't quite be closed I think.
